### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by konstantinkobs** [penpot/penpot#1062]
**Is your feature request related to a problem? Please describe.**
My team would like to use Penpot to create scientific posters. Being able to work on the canvas simultaneously is a great feature and the possibility to create templates is perfect for forcing all posters to have a certain design language. Unfortunately, posters are mostly needed in PDF format, for example for online conferences. Being able to select and copy text is not possible when exporting the poster as an image.

**Describe the solution you'd like**
It would be awesome to add an "Export as PDF" option in the export settings. This way, exported files could be used in settings such as online conferences and would include selectable text and clickable links.

**Describe alternatives you've considered**
I tried to export the poster as an SVG and convert it to a PDF afterwards, however, text is converted to paths during export, so the resulting files did not include selectable text. I am not aware of any feature to prevent the export from converting all text to paths.

**Comment by elhombretecla** [comment]
Hi @konstantinkobs 

Thank you for your feedback. Nice to hear about a complete team of users loving Penpot!

We will develop the export PDF feature as soon as possible. It is in our roadmap and very important to us too :)

**Comment by myfunnyandy** [comment]
We've just released this week the ability to export objects to PDF. This feature is in a very early stage, next step will be allowing to create a multipage pdf, but it seems enough to cover your use case @konstantinkobs. This includes the selectable text but not the clickable links, something that I guess you could add outside Penpot. My recomendation is that each poster should belong to an [artboard](https://help.penpot.app/user-guide/objects/#artboards) and then set an export to pdf preset for each artboard like the following one:

![image](https://user-images.githubusercontent.com/708713/125953977-61fed6a4-bd7c-46dc-8d56-14d8743e1da4.png)

I hope this is useful to you, just let us know!

**Comment by konstantinkobs** [comment]
Oh wow, that was fast! Thank you very much! We will check it out as soon as it is available in the Docker version. 😊

**Comment by niwinz** [comment]
The next week the new docker images will be available.

**Comment by moritzschepp** [comment]
@niwinz, that's great!

I couldn't find a way to add any hyperlinks to the exported pdf, though. Is that possible somehow?

**Comment by 4015-al** [comment]
Hello, I have started using penpot for warefrimes design recently, and it's great. but I have a suggestion/request regarding Export to PDF feature. If I should open a new issue, instead of using this one, please let me know. 

## Is your feature request related to a problem? Please describe.

Yes, it's related to **Export to PDF** : 

When exporting a Page with many ArtBoards (one for main content, one for the header, ect ... ) layers as PDF, I get a single page containing the ArtBoard layers separated

## Describe the solution you'd like**

I'd like to be able to : 
- have an option to merge all layers from all the artboards
- exclude hidden layers from being exported. and export each artboard to its own PDF page

## Describe alternatives you've considered

- move all objects to the same main artboard
- remove the others artboards
- Export to PDF
