### ISSUE TITLE
Docker image Support ARM64

### ISSUE THREAD

**Issue by GeekWorkCode** [penpot/penpot#1089]
I want to in my arm64 run on the server。

**Comment by niwinz** [comment]
It is already planned but I can't give you a deadline right now.

(All penpot components are already compatible with ARM64, because the https://design.penpot.app already runs 100% on ARM64).

**Comment by niwinz** [comment]
The main blocker right now is exporter image where we can't right now install chrome/chromum dependency (because of the snap issue on ubuntu immages, snap does not works on docker...)


We do not have this problem with x86 because puppeteer dependency already download a prebuild one for x86 but not for ARM

**Comment by niwinz** [comment]
![image](https://user-images.githubusercontent.com/843689/133277616-17f6e724-2fc9-45be-b4b8-ae600160fb67.png)

Already available since 1.8.0-alpha.
