### ISSUE TITLE
Online automatic saving ?

### ISSUE THREAD

**Issue by Kayoku** [penpot/penpot#1139]
Hi !

**Is your feature request related to a problem? Please describe.**
When I'm working online with penpot, I had frequently some "lag" because of the "automatic save" functionality

**Describe the solution you'd like**
I think it would be interesting to have an option for disable automatic saving, and add a shortcut (like ctrl+s) for saving when you want to save your work.

**Additional context**
I'm not working with a very powerful computer, neither a big connection, it probably accentuate my problem, but I think it can be more comfortable with this solution !

Maybe that the functionality already exist but I don't find it, so sorry if it's the case.

**Comment by myfunnyandy** [comment]
Hi!

We know that for some computer+conexion combination setups it might be a bit slower and have plans to improve synchronization and even allowing working offline, but I'm afraid is not going to happen in the near future. 

Thanks for your feedback, we will take it into account :)

**Comment by Attmin** [comment]
I agree with @Kayoku. The auto-save version sometimes doesn't seem to save the current draft. When I switch to view mode, it shows an earlier version that is not the edited version and the auto save gets stuck on the old version.

I think this should be a high priority because this tool has really amazing features, but when I can't save my work properly it's a bit annoying.

**Comment by JPustkuchen** [comment]
Perhaps the "Saved" state could be indicated in the footer and pressing Ctrl+s might trigger an explicit save?
Saw something similar at ClickUp and it works great!

**Comment by myfunnyandy** [comment]
Penpot's performance has improved a lot since this issue was raised and the autosave saves changes in a matter of few seconds. What we are finding is that certain users are so attached to press ctrl+s while working that are asking us to implement it basically to prevent the browser save prompt from launching. This could make us considering making this changes, but we are still reluctant as this stills feel as a workaround to avoid a familiarity issue.

**Comment by danielle-h** [comment]
I see this as well, though I am not sure it is only connected to the autosaving. I have 11 boards in one file, and I find that performance is very laggy, especially when saving. Also, the save itself can be slow in this case, and it autosaves every few seconds. Perhaps an option to set autosave to every minute instead of every few seconds?
I didn't try to press ctrl+s even once ;)

**Comment by madalenapmelo-kp** [comment]
Since the performance has been dramatically improved and we will continue working on improving it further, disabling automatic saving is not something that we plan to address in the foreseeable future so I'm closing this issue.
