### ISSUE TITLE
Double click icon in navigation pane to focus on object or artboard

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1159]
**Is your feature request related to a problem? Please describe.**
I have many artboards on my page and navigating to them with scrolling and mouse dragging can be cumbersome

**Describe the solution you'd like**
Similar to Figma, I would like to be able to double-click the icon of the object or artboard in the navigation pane and that would focus my window onto the selected object or artboard

**Describe alternatives you've considered**
Can't think of other ways to do this :/

**Additional context**
I'm referring to the icons next to the object or artboard name
![image](https://user-images.githubusercontent.com/46250921/131018850-1a642fde-00a5-4fee-8500-b137c1e647a6.png)

**Comment by elhombretecla** [comment]
Hi @jsmorabito :)

We will review this enhancement and take it into account for the future.
[https://tree.taiga.io/project/penpot/issue/1962](https://tree.taiga.io/project/penpot/issue/1962)

Thank you so much!

**Comment by andrewzhurov** [comment]
Having this would make Penpot's interface more akin to Figma's, lowering learning curve for Figma users, making it easier for them to transition.
I used Figma just for a little bit and even with that brief exposure opening Penpot I tried to double-click on an item to zoom.
This action seems to be pretty basic and important.

After that I learned that there is Shift+2 shortcut to focus on selected item and it seems to be more universal, lowering value of having double-click. But I think there still value in having focus on double-click.
Since:
- not all users know of Shift+2
- interface more akin to Figma - uniform interface makes it easier to transition
- when focusing on an hierarchy item it's easier to double-click than click + Shift+2

**Comment by andrewzhurov** [comment]
Also, the way I found about Shift+2 "Zoom to selected" is from the zoom contextual menu
![image](https://user-images.githubusercontent.com/13056889/179481920-d5ffd48c-fe9c-47e4-a4a6-6450a62f3562.png)
which is, perhaps, not the most discoverable way, I stumbled on it rather by accident.

Perhaps listing this shortcut in contextual menus would make it more discoverable?
![image](https://user-images.githubusercontent.com/13056889/179481567-81499704-62a3-4a0c-b1e6-54827bf6aeed.png)
![image](https://user-images.githubusercontent.com/13056889/179482555-2ffc9adc-c4f9-4a69-acf8-349b7453184c.png)
