### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by weaktyper** [penpot/penpot#36]
I've started the docker container but I'm unfamiliar with `tmux` and not sure how to use it. 

I'm not even sure what to look for,  are there screenshots anywhere to help get started?

**Comment by jdittrich** [comment]
Same problem here. I remember that I successfully used this project in the past, but I don't remember the need to `tmux` explicitly.

**Comment by niwinz** [comment]
Tmux is just a helper for run many things in one unique docker container, you need to lear a very small shortcuts in order to get you proficient with it, and there are a lot of documentations on how-to's on how to use tmux.

On the end, it is a terminal multiplexor, it is opened in the docker container and starts 3 different subterminals each one running different processes: gulp, figwheel, and the backend.

**Comment by weaktyper** [comment]
@niwinz 
But How do I start the UX frontend ? -- do I need to open it in a browser at `localhost` and do I need to run any command for the `frontend` or `backend`.

**Comment by niwinz** [comment]
when the figwheel is up and running (in tmux together with the gulp), just go to `http://localhost:3449` on your browser.

**Comment by weaktyper** [comment]
thanks, I'll try this soon and see how i get on.

**Comment by weaktyper** [comment]
See the errors in issue 35 when trying to start.
