### ISSUE TITLE
Can't reach lower items in left design board menu

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#689]
**Describe the bug**
Due to my laptop having a small screen (1366x768), I can't see all the items in the left design board menu. The last icon I can see (half) is 'Assets'; when hitting F11 the last icon I see is 'Colour palette'.

**To Reproduce**
1.  Take an old laptop with a small screen
2.  Log in to Penpot :)
4.  See error

**Expected behavior**
The menu is scrollable on small screens

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/11229646/108963748-cea5eb80-767a-11eb-8eb6-e8762312d540.png)

**Desktop (please complete the following information):**
-   OS: Ubuntu
-   Browser Firefox
-   Version (e.g. 22) of the OS or the browser?

**Environment:**
using SAAS (https://design.penpot.app)

**Comment by myfunnyandy** [comment]
Hi, this will be fixed in the next release. You can see in the attached screenshot how the toolbar will look with the resolution you mentioned. We are also considering some tools reorganization so everything will be accessible for even smaller heights ([Taiga user story](https://tree.taiga.io/project/penpot/us/1249?no-milestone=1)).

Nice design by the way ;)

![Screenshot from 2021-02-24 09-00-44](https://user-images.githubusercontent.com/708713/108966771-e5e6d800-767e-11eb-9a6d-6fe83815fe6e.png)

**Comment by keunes** [comment]
Thanks for the quick reply @myfunnyandy! I should've noted that due to Firefox & OS bars, effective size available in the browser is 1.296 × 637. But given the space left in the screenshot you shared, I assume that'll be fine.

Should I close this, given the user story in Taiga?

PS: that design is courtesy of the AntennaPod developers - so far I had just imported a screenshot haha

**Comment by hirunatan** [comment]
@keunes when we add a Taiga story for an issue, we are leaving the issue in github open, with a tag, so people can track it from here if they want.

**Comment by myfunnyandy** [comment]
As we already did a basic fix for this and the mectioned Taiga US is about further enhancements I'm closing this issue.
