### ISSUE TITLE
List uploaded images under 'Assets'

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#693]
**Is your feature request related to a problem? Please describe.**
 I'm aiming to create a mock-up for a new feature in AntennaPod (Android app). To save myself some time replicating standard components (like the android top bar and the app's top bar), I imported a screenshot from the app that I'd like to reuse across different artboards. I currently don't see a quick way to reuse these images I uploaded (probably copy-paste will work?)

**Describe the solution you'd like**
Under 'Assets', above/below 'File library' add a new item 'Uploaded to this board', with the images listed below (as is currently done for graphics part of a actual library). From there, display the number of times the upload is used in the project, and provide a delete button (if I uploaded a wrong file, it's helpful if it is automatically after a while or manually can be deleted).

**Describe alternatives you've considered**
List them under 'File library' - but I reckon this is strictly for 'libraries' - which uploads aren't part of?

**Additional context**

**Comment by hirunatan** [comment]
Images uploaded directly to your file are not listed in assets, since they are used only in the image shape created for it. If you delete the shape, the image is automatically removed from the file later.

Assets are for elements that are intended to be reused. If you want to use the same image in several places, upload it as an asset, in the "Graphics" section, and then drag and drop it everywhere you need.
