### ISSUE TITLE
Paths should have a fill colour of "none".

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#71]
When paths are created, the default fill colour is black at an opacity of 0%. However, this is confusing because the path is not filled (the first thing you see is the black palette, my eye did not go further to see the opacity setting). If it were set to "none", it would be more intuitive. Inkscape has a "no fill" button (see below).
![ink_colour](https://cloud.githubusercontent.com/assets/4901306/23488326/133bc064-ff40-11e6-9d57-4dc17b0089ec.jpg)

Further, even when you change the colour, the path does not change, because opacity is 0%. If you change from a colour of "none", to some colour, the opacity should default to 100%.
Maybe, something like this?
![fill2](https://cloud.githubusercontent.com/assets/4901306/23488717/7e915142-ff42-11e6-978e-76ae10da3c3f.jpg)

**Comment by niwinz** [comment]
There are clearly a lot of margin of improvement. But at this moment, uxbox does not support the notion of **no fill**, this is because the opacity 0 is used.

You are right on your suggestion y we possibly need to revisit that in the near future. The current focus is mainly fix big usability problems and bugs. So I'll mark this as enhancement and we will return to it soon.
