### ISSUE TITLE
Highlight interactive elements by default

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#721]
**Is your feature request related to a problem? Please describe.**
I'm sharing the (pre)view of my interactive design with people on the forum of the project I'm contributing to. They're not familiar with Penpot or similar tools. The eye icon in the  view screen is not descriptive.

**Describe the solution you'd like**
Highlight interactive elements by default, so that anyone will get an immediate indication of where they can click - even if they're not familiar with the tool.
The colour overlay should maybe be made a bit less strong, as it affects/hides the colours in my design. I feel the border and cursor style are sufficient as indicator of the clickable area; the colour overlay is mainly important for background/hidden elements where the border might not be visible.

**Describe alternatives you've considered**
* Replace the eye icon with text, so it's clearer to users without knowledge of the tool how they can highlight interactive elements.
* Allow to select default view when sharing the view link.

**Additional context**

**Comment by niwinz** [comment]
thanks @keunes for the feedback, I have created the [enhacement in taiga](https://tree.taiga.io/project/penpot/issue/1330) for tracking it.

**Comment by jancborchardt** [comment]
Yep – the setting "Show interactions on click" is something known from other tools like Marvel and is a nice default.

In Penpot, it seems to always be reset to "Don’t show interactions":
![Show interactions on click should be default](https://user-images.githubusercontent.com/925062/117286342-5b360c80-ae69-11eb-94e9-be9cede8bd88.png)

**Comment by keunes** [comment]
Hi @myfunnyandy,
If I may, I would like to add two additional thoughts on this:
* your choice gets reset when the page is refreshed (e.g. if in the prototype 'edit' view I press 'play' again), as Jan noted/implied also. It'd be great if my choice would be maintained (at least during browser session)
* when saving/sharing a link, it'd be great if I can include this setting in the URL (even if manually, not exposed as setting in UI); when sharing a view with the wider community (who are not accstomed to interactive mock-ups) having the interactions shown will be helpful

**Comment by NicolasLeboeuf** [comment]
bump.

I'd like that displaying the interactions is by default. Or at least having the possibility to set it by default.

**Comment by myfunnyandy** [comment]
Hi all, I'm taking up this matter. The proposals here expressed should clearly improve the "Show interactions" setting. Thanks! 

I've created a separate enhancement to isolate a solution that both meet the needs (improve the discoverability of the interactions and persistence of the setting) and its feasible in the short term (the settings when creating the interactions could definitely take longer).

I've created it adding the "good first issue" so it's shown at the [Contributions page](https://github.com/penpot/penpot/labels/good%20first%20issue) as it seem that this could be a good one to be made by a community member just in case we don't do it before at the core team (that's why we're keeping track of it [at Taiga](https://tree.taiga.io/project/penpot/us/5440?backlog-status=2076387,2076388,2501717,2135486&backlog-q=interactions&no-milestone=1) too).
