### ISSUE TITLE
Stroke doesn't get updated when group gets 50% transparency

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#729]
Sorry for creating so many issues while it's still an early alpha - you're probably aware of these things already.

**Describe the bug**
When a circle is part of a group, and has a stroke with a colour defined in the assets, the stroke doesn't get update when giving the group a transparency of 50%. All other elements are overridden.

**To Reproduce**
1.  Create a group with multiple elements, of which one is a circle with a stroke with a linked colour
2.  Click on the group
3.  Go to 'group fill', type 50% and hit enter
4.  See error

**Expected behavior**
Stroke colour gets unlinked and 50% opacity

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/11229646/109810438-d0971e00-7c29-11eb-87d4-dc11b11ffe07.png)

After manual correction:
![afbeelding](https://user-images.githubusercontent.com/11229646/109810515-e86ea200-7c29-11eb-8aca-748b7c72e449.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 18.04
-   Browser: Firefox 86.0

**Environment (please complete the following information):**
using SAAS (https://design.penpot.app)

**Comment by hirunatan** [comment]
Thanks for the freedback. Don't worry, this is useful for us, we'll keep taking note of everything, and deal with it when we can.

Related issue in Taiga: https://tree.taiga.io/project/penpot/issue/1367

**Comment by Alotor** [comment]
@keunes we really appreciate that you take the time to report issues, doesn't bother us at all.

The thing with this issue is that, as I understand, what you want is to adjust the opacity of the shape as a whole (fill + stroke). That feature is already done and will be available in the next release.

Please, check it for next release and if you think that's not it we can reopen this issue.
