### ISSUE TITLE
File saving issue 

### ISSUE THREAD

**Issue by akhilpt07** [penpot/penpot#786]
There are some issues with saving the. if file can save locally on the machine which will help to continue the work with out any need of the internet

**Comment by niwinz** [comment]
Can you explain a bit more, I'm not clearly understand the problem.

**Comment by akhilpt07** [comment]
if the internet goes offline we can't continue the work. So if there is feature for saving the file locale will help to continue the work with out internet.

**Comment by niwinz** [comment]
Still do not completly understand... maybe you are supposing something that I'm not aware of. But right now, the only way to work without the internet connection is having the penpot deployed locally using docker, but for this, you don't need to save it locally because they are already stored locally, and you can access the penpot deployed on your personal laptop.

So I feel I miss some info here to completly undestand you.

**Comment by akhilpt07** [comment]
Yes your are correct. but issue is we can't continue the work after internet goes offline
![Penpot](https://user-images.githubusercontent.com/58035189/112629584-82f18800-8e5a-11eb-94f1-71581c3df383.jpg)

**Comment by niwinz** [comment]
So, for confirm, you are running an on-premise instance, using docker on your local laptop, and when you lose internet you unable to access penpot on your local docker instance.

Please, you need to provide more context information for us to understand, the application can be executed/used in many different ways. We cannot guess information that we do not know. It is not the same that you cannot use the SAAS service offline, than use a local instance offline.

**Comment by akhilpt07** [comment]
I am using penpot in firefox not on docker.

**Comment by niwinz** [comment]
Ok, we will take your feedback in consideration. It is not a bug, it just right now there are no way to use penpot offline without installing it on your laptop/personal computer.
Thanks.
