### ISSUE TITLE
Not clear who got invited already

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#907]
**Is your feature request related to a problem? Please describe.**
Currently it is unclear who was invited already. You do get a short "Invitation sent" confirmation, but then until they accept the invitation, the system does not give feedback about who already had an invite sent to them.

**Describe the solution you'd like**
Simply showing the "Pending invitations" on top of the list, so you directly see who might need assistance or where there might be issues.

**Describe alternatives you've considered**
Here is how GitHub does it with an extra filter – but this is always a bit cumbersome to get to, and a level of complexity not really needed yet at this point.
![Github pending and failed invitations](https://user-images.githubusercontent.com/925062/117279151-b7952e00-ae61-11eb-9fd7-5c5ef97a0ce7.png)

**Comment by niwinz** [comment]
Yeah, we are aware of this problem, and we UX/Design team is already working on a better solution. We don't have a concrete Taiga US to refer because this is covered by others at simple view unrelated US's.

For more context: the current approach was just a MVP for the first public alpha and we are aware of the current limitations. This is a high priority for us bug we want to fix it in a proper way additionally to improvements to the current permissions subsystem.

**Comment by jancborchardt** [comment]
Thanks for the info @niwinz! :) Yep, I’m totally aware that it’s alpha state, and I totally love it already. Great work!

**Comment by niwinz** [comment]
The invitation page was reworked some versions ago, so I think this should be considered done.
Thanks for reporting.
